const { test } = require('node:test');
const assert = require('node:assert');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const dsh = require('../tools/sync/lib/dsh-instructions');

const BEGIN = '<!-- myrules:begin -->';
const END = '<!-- myrules:end -->';

const fakeManifest = {
  dsh: { blockBegin: BEGIN, blockEnd: END },
};

function makeRulesDir(files) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'myrules-dsh-rules-'));
  for (const [name, body] of Object.entries(files)) {
    fs.writeFileSync(path.join(dir, name), body);
  }
  return dir;
}

function tmpFile(name = 'AGENTS.md') {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'myrules-dsh-agents-'));
  return path.join(dir, name);
}

test('buildBlock renders markers, a generated notice, and one section per topic', () => {
  const block = dsh.buildBlock({
    begin: BEGIN,
    end: END,
    sections: [{ topic: 'testing', body: '# Testing\n\n- write tests' }],
  });
  assert.ok(block.startsWith(BEGIN));
  assert.ok(block.endsWith(END));
  assert.match(block, /generated by myrules sync/);
  assert.match(block, /## myrules: testing\n\n# Testing\n\n- write tests/);
});

test('deployProjectInstructions creates AGENTS.md with the managed block', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing\n\n- write tests' });
  const agentsFile = tmpFile();
  const result = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
  });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.ok(text.startsWith(BEGIN), text);
  assert.match(text, /## myrules: testing/);
  assert.strictEqual(result.wrote, true);
  assert.strictEqual(result.drifted, false);
  assert.ok(result.blockHash);
});

test('deployProjectInstructions preserves existing user content outside the block', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing' });
  const agentsFile = tmpFile();
  fs.writeFileSync(agentsFile, '# My project\n\n- user rule\n');

  dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.ok(text.startsWith('# My project\n\n- user rule\n'), text);
  assert.ok(text.includes(BEGIN));
});

test('deployProjectInstructions is idempotent on a second run', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing' });
  const agentsFile = tmpFile();
  const first = dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });
  const afterFirst = fs.readFileSync(agentsFile, 'utf8');

  const second = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: first.blockHash,
  });
  assert.strictEqual(second.wrote, false);
  assert.strictEqual(second.drifted, false);
  assert.strictEqual(fs.readFileSync(agentsFile, 'utf8'), afterFirst);
});

test('deployProjectInstructions updates the block when rule content changes', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing\n\n- v1' });
  const agentsFile = tmpFile();
  const first = dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  fs.writeFileSync(path.join(rulesDir, 'myrules-testing.md'), '# Testing\n\n- v2');
  const second = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: first.blockHash,
  });

  assert.strictEqual(second.wrote, true);
  assert.strictEqual(second.drifted, false);
  assert.match(fs.readFileSync(agentsFile, 'utf8'), /- v2/);
});

test('deployProjectInstructions skips a hand-edited block and reports drift', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing' });
  const agentsFile = tmpFile();
  const first = dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  const text = fs.readFileSync(agentsFile, 'utf8').replace('## myrules: testing', '## myrules: tampered');
  fs.writeFileSync(agentsFile, text);

  fs.writeFileSync(path.join(rulesDir, 'myrules-testing.md'), '# Testing\n\n- v2');
  const second = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: first.blockHash,
  });

  assert.strictEqual(second.drifted, true);
  assert.strictEqual(second.wrote, false);
  assert.match(fs.readFileSync(agentsFile, 'utf8'), /myrules: tampered/);
});

test('deployProjectInstructions with force overwrites the block but keeps outside content', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing' });
  const agentsFile = tmpFile();
  fs.writeFileSync(agentsFile, '# User heading\n');
  const first = dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  fs.writeFileSync(agentsFile, fs.readFileSync(agentsFile, 'utf8').replace('## myrules: testing', '## myrules: tampered'));
  fs.writeFileSync(path.join(rulesDir, 'myrules-testing.md'), '# Testing\n\n- v2');

  const second = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: first.blockHash,
    force: true,
  });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.strictEqual(second.drifted, false);
  assert.ok(text.startsWith('# User heading\n'));
  assert.match(text, /- v2/);
  assert.doesNotMatch(text, /tampered/);
});

test('deployProjectInstructions drops sections whose rule files were removed', () => {
  const rulesDir = makeRulesDir({
    'myrules-testing.md': '# Testing',
    'myrules-review.md': '# Review',
  });
  const agentsFile = tmpFile();
  const first = dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  fs.rmSync(path.join(rulesDir, 'myrules-review.md'));
  const second = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: first.blockHash,
  });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.strictEqual(second.wrote, true);
  assert.match(text, /myrules: testing/);
  assert.doesNotMatch(text, /myrules: review/);
});

test('deployProjectInstructions appends extraSections after rule sections', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing' });
  const agentsFile = tmpFile();
  dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    extraSections: [{ topic: 'roles', body: '角色工具表' }],
  });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.match(text, /## myrules: roles\n\n角色工具表/);
  assert.ok(text.indexOf('## myrules: testing') < text.indexOf('## myrules: roles'));
});

test('deployUserInstructions writes ~/.dsh/AGENTS.md from the user rules dir', () => {
  const rulesDir = makeRulesDir({ 'myrules-user-preferences.md': '# Preferences\n\n- be concise' });
  const agentsFile = tmpFile('AGENTS.md');
  const result = dsh.deployUserInstructions({ manifest: fakeManifest, rulesDir, agentsFile });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.match(text, /## myrules: user-preferences/);
  assert.strictEqual(result.wrote, true);
});

test('budgetWarning flags combined blocks over the threshold', () => {
  assert.ok(dsh.budgetWarning(50 * 1024, 10 * 1024));
  assert.strictEqual(dsh.budgetWarning(100, 200), null);
});

test('deployProjectInstructions ignores non-managed files in the rules dir', () => {
  const rulesDir = makeRulesDir({
    'myrules-testing.md': '# Testing',
    'old-style.md': '# Legacy hand file',
  });
  const agentsFile = tmpFile();
  dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.match(text, /## myrules: testing/);
  assert.doesNotMatch(text, /Legacy hand file/);
});

test('upsertBlock reports drift instead of stacking a second block when the end marker is missing', () => {
  const agentsFile = tmpFile();
  fs.writeFileSync(agentsFile, `# User\n\n${BEGIN}\n\n## myrules: tampered\n\nbroken block without end\n`);

  const block = dsh.buildBlock({ begin: BEGIN, end: END, sections: [{ topic: 'testing', body: '# T' }] });
  const result = dsh.upsertBlock(agentsFile, block, { begin: BEGIN, end: END });

  assert.strictEqual(result.drifted, true);
  assert.strictEqual(result.wrote, false);
  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.strictEqual(text.split(BEGIN).length - 1, 1, 'must not append a second block');
  assert.strictEqual(text.split(END).length - 1, 0);
});

test('upsertBlock force repairs a block only inside markers', () => {
  const agentsFile = tmpFile();
  fs.writeFileSync(agentsFile, `# User\n\n${BEGIN}\n\n## myrules: tampered\n\n${END}\n\n# tail\n`);
  const block = dsh.buildBlock({ begin: BEGIN, end: END, sections: [{ topic: 'testing', body: '# T' }] });

  const result = dsh.upsertBlock(agentsFile, block, { begin: BEGIN, end: END, force: true });

  const text = fs.readFileSync(agentsFile, 'utf8');
  assert.strictEqual(result.wrote, true);
  assert.ok(text.startsWith('# User\n\n'));
  assert.ok(text.trimEnd().endsWith('# tail'));
  assert.doesNotMatch(text, /tampered/);
});

test('a hand-edited block is still skipped on the next run (never silently overwritten)', () => {
  const rulesDir = makeRulesDir({ 'myrules-testing.md': '# Testing\n\n- v1' });
  const agentsFile = tmpFile();
  const first = dsh.deployProjectInstructions('/tmp/whatever', { manifest: fakeManifest, rulesDir, agentsFile });

  fs.writeFileSync(
    agentsFile,
    fs.readFileSync(agentsFile, 'utf8').replace('## myrules: testing', '## myrules: tampered')
  );
  fs.writeFileSync(path.join(rulesDir, 'myrules-testing.md'), '# Testing\n\n- v2');

  const second = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: first.blockHash,
  });
  assert.strictEqual(second.drifted, true);
  assert.strictEqual(second.wrote, false);

  // 旧实现在这一轮会把手改块覆盖掉：必须依旧 drift、依旧保留手改
  const third = dsh.deployProjectInstructions('/tmp/whatever', {
    manifest: fakeManifest,
    rulesDir,
    agentsFile,
    priorHash: second.blockHash,
  });
  assert.strictEqual(third.drifted, true);
  assert.strictEqual(third.wrote, false);
  assert.match(fs.readFileSync(agentsFile, 'utf8'), /myrules: tampered/);
});

test('upsertBlock without a prior hash does not overwrite a differing existing block', () => {
  const agentsFile = tmpFile();
  // 模拟 state 丢失/老版本升级：块已存在且与新块不同
  fs.writeFileSync(agentsFile, `${BEGIN}\n\n## myrules: testing\n\n# stale block\n${END}\n`);
  const block = dsh.buildBlock({ begin: BEGIN, end: END, sections: [{ topic: 'testing', body: '# Testing' }] });

  const result = dsh.upsertBlock(agentsFile, block, { begin: BEGIN, end: END });
  assert.strictEqual(result.drifted, true);
  assert.strictEqual(result.wrote, false);
  assert.match(fs.readFileSync(agentsFile, 'utf8'), /# stale block/);
});
