const fs = require('node:fs');
const path = require('node:path');
const paths = require('./paths');

const MARKER = '# MyRules deploy artifacts (generated by myrules sync — edit ~/.myrules/rules/ instead)';

function buildBlock(manifest, runtime = 'agent') {
  const prefix = manifest.managedPrefix;
  const backupDir = manifest.prune.backupDir;
  const agentPrefix = manifest.agents?.prefix || prefix;
  const stateFile = path.basename(paths.getStateFilePath('.'));
  const lines = [
    MARKER,
    `.cursor/rules/${prefix}*`,
    `!.cursor/rules/${prefix}method-*`,
    `.claude/rules/${prefix}*`,
    `!.claude/rules/${prefix}method-*`,
    `.opencode/rules/${prefix}*`,
    `!.opencode/rules/${prefix}method-*`,
    `.dsh/rules/${prefix}*`,
    `!.dsh/rules/${prefix}method-*`,
  ];
  if (runtime !== 'project') {
    lines.push(
      `.cursor/agents/${agentPrefix}*`,
      `.claude/agents/${agentPrefix}*`,
      `.opencode/agents/${agentPrefix}*`,
      `.dsh/agents/${agentPrefix}*`
    );
  }
  lines.push(`.cursor/hooks/${prefix}*`, `${backupDir}/`, `${stateFile}`);
  const dshRows = manifest.dsh?.rolesRowsFile;
  if (dshRows) lines.push(String(dshRows).replace(/\\/g, '/'));
  return lines.join('\n');
}

function newlineOf(text) {
  return text.includes('\r\n') ? '\r\n' : '\n';
}

function normalizeBlock(text) {
  return text.replace(/\r\n/g, '\n').replace(/\n+$/, '');
}

/** Exclusive end index of the MyRules gitignore block starting at MARKER. */
function blockEndIndex(existing, start, nl) {
  let pos = start;
  while (pos < existing.length) {
    const nextNl = existing.indexOf(nl, pos);
    const lineEnd = nextNl === -1 ? existing.length : nextNl;
    const line = existing.slice(pos, lineEnd);
    if (pos !== start && line.trim() === '') return pos;
    if (nextNl === -1) return existing.length;
    pos = nextNl + nl.length;
  }
  return existing.length;
}

function ensureGitignore(projectRoot, manifest, runtime = 'agent') {
  const file = path.join(projectRoot, '.gitignore');
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  const block = buildBlock(manifest, runtime);
  const start = existing.indexOf(MARKER);

  if (start === -1) {
    const separator = existing.length === 0 ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
    fs.writeFileSync(file, existing + separator + block + '\n');
    return true;
  }

  const nl = newlineOf(existing);
  const end = blockEndIndex(existing, start, nl);
  const current = existing.slice(start, end);
  if (normalizeBlock(current) === block) return false;

  fs.writeFileSync(file, existing.slice(0, start) + block + nl + existing.slice(end));
  return true;
}

module.exports = { ensureGitignore, MARKER, buildBlock };
