const fs = require('node:fs');
const path = require('node:path');
const paths = require('./paths');

const MARKER = '# MyRules deploy artifacts (generated by myrules sync — edit ~/.myrules/rules/ instead)';

function buildBlock(manifest) {
  const prefix = manifest.managedPrefix;
  const backupDir = manifest.prune.backupDir;
  const stateFile = path.basename(paths.getStateFilePath('.'));
  return [
    MARKER,
    `.cursor/rules/${prefix}*`,
    `.claude/rules/${prefix}*`,
    `${backupDir}/`,
    `${stateFile}`,
  ].join('\n');
}

function ensureGitignore(projectRoot, manifest) {
  const file = path.join(projectRoot, '.gitignore');
  const existing = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
  if (existing.includes(MARKER)) return false;

  const block = buildBlock(manifest);
  const separator = existing.length === 0 ? '' : existing.endsWith('\n') ? '\n' : '\n\n';
  fs.writeFileSync(file, existing + separator + block + '\n');
  return true;
}

module.exports = { ensureGitignore, MARKER, buildBlock };
